# Generated by Django 3.1.3 on 2021-02-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('School', models.CharField(default='No-School', max_length=20)),
                ('Group', models.IntegerField(default=0)),
                ('password', models.CharField(default='000000000000', max_length=20)),
                ('filename', models.CharField(default='No-File-name', max_length=20)),
                ('Identity', models.CharField(default='No-Identiy', max_length=20)),
            ],
        ),
    ]
